# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/client/documentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Documentation(object):
    def setupUi(self, Documentation):
        Documentation.setObjectName("Documentation")
        Documentation.resize(800, 600)
        Documentation.setMinimumSize(QtCore.QSize(800, 600))
        Documentation.setMaximumSize(QtCore.QSize(1600, 1200))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        Documentation.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Documentation)
        self.centralwidget.setObjectName("centralwidget")
        self.MarkdownView = QtWidgets.QTextEdit(self.centralwidget)
        self.MarkdownView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.MarkdownView.setAcceptDrops(False)
        self.MarkdownView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MarkdownView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MarkdownView.setLineWidth(0)
        self.MarkdownView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.MarkdownView.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.MarkdownView.setUndoRedoEnabled(False)
        self.MarkdownView.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MarkdownView.setObjectName("MarkdownView")
        Documentation.setCentralWidget(self.centralwidget)

        self.retranslateUi(Documentation)
        QtCore.QMetaObject.connectSlotsByName(Documentation)

    def retranslateUi(self, Documentation):
        _translate = QtCore.QCoreApplication.translate
        Documentation.setWindowTitle(_translate("Documentation", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Documentation = QtWidgets.QMainWindow()
    ui = Ui_Documentation()
    ui.setupUi(Documentation)
    Documentation.show()
    sys.exit(app.exec_())
